# Generated by Django 5.2.11 on 2026-02-17 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('active_shares', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='share',
            name='buyers',
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Nombre de parts achetées')),
                ('purchased_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'achat")),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='active_shares.buyer')),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='active_shares.share')),
            ],
            options={
                'verbose_name': 'Achat',
                'verbose_name_plural': 'Achats',
                'ordering': ['-purchased_at'],
            },
        ),
    ]
