# Generated by Django 5.2.11 on 2026-02-17 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('active_shares', '0002_remove_old_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='buyers',
            field=models.ManyToManyField(related_name='purchased_shares', through='active_shares.Purchase', to='active_shares.buyer', verbose_name='Acheteurs'),
        ),
    ]
